bag/urls.py
from django.urls import path
from . import views

app_name = 'bag'

urlpatterns = [
    path('', views.bag_detail, name='bag_detail'),
    path('add/<int:product_id>/', views.add_to_bag, name='add_to_bag'),
    path('update/<int:item_id>/', views.update_bag_item, name='update_bag_item'),
    path('remove/<int:item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

relish/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'roastery.views.custom_page_not_found'
handler403 = 'roastery.views.custom_permission_denied_view'


urlpatterns = [
    path("admin/", admin.site.urls),
    path("summernote/", include("django_summernote.urls")),
    path("", include("roastery.urls"), name="roastery-urls"),
    path("accounts/", include("accounts.urls")),
    path("", include("django.contrib.auth.urls")),
    path("roastery/", include("roastery.urls")),
    path("", include("roastery.urls")),
    path("bag/", include("bag.urls")),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
]

roastery/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="home"),
    path("origin/<str:continent_name>/", views.origin_products,
         name="origin_products"),
    path("product/<int:product_id>/", views.product_detail,
         name="product_detail"),
    path("manage/", views.manage_products, name="manage_products"),
    path("create/", views.create_product, name="create_product"),
    path('products/', views.products_list, name='products'),
    path("update/<int:product_id>/", views.update_product,
         name="update_product"),
    path("delete-product/<int:product_id>/", views.delete_product,
         name="delete_product"),
    path("denied", views.custom_permission_denied_view, name="denied"),
]

roastery/models.py
from django.db import models
from django.utils.text import slugify
from cloudinary.models import CloudinaryField

# Create your models here.
GRIND_CHOICES = (
    (0, "Whole Bean"),
    (1, "Coarse"),
    (2, "Medium"),
    (3, "Fine"),
    (4, "Extra Fine")
)

GRIND_CHOICES_DICT = dict(GRIND_CHOICES)


CONTINENT_CHOICES = (
    (0, "African"),
    (1, "Asian"),
    (2, "American"),
)


COUNTRY_CHOICES = (
    (0, "Ethiopia"),
    (1, "Kenya"),
    (2, "Uganda"),
    (3, "India"),
    (4, "Vietnam"),
    (5, "Brazil"),
    (6, "Colombia"),
    (7, "Guatemala"),
    (8, "Peru"),
)


REGION_CHOICES = (
    (0, "Sidamo"),
    (1, "Blue Mountain"),
    (2, "Agua Santa"),
    (3, "Excelso Popayan"),
    (4, "Huehuetenango"),
    (5, "Copaceyba"),
    (6, "Malabar"),
    (7, "-")
)

CURRENCY_CHOICES = (
    ("USD", "USD - US Dollar"),
    ("EUR", "EUR - Euro"),
    ("GBP", "GBP - British Pound Sterling"),
    ("JPY", "JPY - Japanese Yen"),
    ("AUD", "AUD - Australian Dollar"),
    ("CAD", "CAD - Canadian Dollar"),
    ("CHF", "CHF - Swiss Franc"),
    ("CNY", "CNY - Chinese Yuan"),
    ("SEK", "SEK - Swedish Krona"),
    ("NZD", "NZD - New Zealand Dollar"),
    ("MXN", "MXN - Mexican Peso"),
    ("SGD", "SGD - Singapore Dollar"),
    ("HKD", "HKD - Hong Kong Dollar"),
    ("NOK", "NOK - Norwegian Krone"),
    ("KRW", "KRW - South Korean Won"),
    ("TRY", "TRY - Turkish Lira"),
    ("INR", "INR - Indian Rupee"),
    ("RUB", "RUB - Russian Ruble"),
    ("ZAR", "ZAR - South African Rand"),
    ("BRL", "BRL - Brazilian Real"),
    ("ILS", "ILS - Israeli New Shekel"),
    ("PLN", "PLN - Polish Zloty"),
    ("THB", "THB - Thai Baht"),
    ("DKK", "DKK - Danish Krone"),
    ("HUF", "HUF - Hungarian Forint"),
    ("CZK", "CZK - Czech Koruna"),
    ("CLP", "CLP - Chilean Peso"),
    ("COP", "COP - Colombian Peso"),
    ("PEN", "PEN - Peruvian Sol"),
    ("ARS", "ARS - Argentine Peso"),
    ("MYR", "MYR - Malaysian Ringgit"),
    ("PHP", "PHP - Philippine Peso"),
    ("PKR", "PKR - Pakistani Rupee"),
    ("MAD", "MAD - Moroccan Dirham"),
    ("AED", "AED - United Arab Emirates Dirham"),
    ("BHD", "BHD - Bahraini Dinar"),
    ("KWD", "KWD - Kuwaiti Dinar"),
    ("OMR", "OMR - Omani Rial"),
    ("JOD", "JOD - Jordanian Dinar"),
    ("DZD", "DZD - Algerian Dinar"),
    ("TND", "TND - Tunisian Dinar"),
)

CURRENCY_SYMBOLS = (
    ("USD", "$"),
    ("EUR", "€"),
    ("GBP", "£"),
    ("JPY", "¥"),
    ("AUD", "A$"),
    ("CAD", "C$"),
    ("CHF", "CHF"),
    ("CNY", "¥"),
    ("SEK", "kr"),
    ("NZD", "NZ$"),
    ("MXN", "$"),
    ("SGD", "S$"),
    ("HKD", "HK$"),
    ("NOK", "kr"),
    ("KRW", "₩"),
    ("TRY", "₺"),
    ("INR", "₹"),
    ("RUB", "₽"),
    ("ZAR", "R"),
    ("BRL", "R$"),
    ("ILS", "₪"),
    ("PLN", "zł"),
    ("THB", "฿"),
    ("DKK", "kr"),
    ("HUF", "Ft"),
    ("CZK", "Kč"),
    ("CLP", "$"),
    ("COP", "$"),
    ("PEN", "S/"),
    ("ARS", "$"),
    ("MYR", "RM"),
    ("PHP", "₱"),
    ("PKR", "₨"),
    ("MAD", "د.م."),
    ("AED", "د.إ"),
    ("BHD", "ب.د."),
    ("KWD", "د.ك"),
    ("OMR", "ر.ع."),
    ("JOD", "د.أ"),
    ("DZD", "د.ج"),
    ("TND", "د.ت"),
)


class Category(models.Model):
    category_id = models.BigAutoField(primary_key=True)
    main_category = models.CharField(max_length=100)

    def __str__(self):
        return self.main_category


class CoffeeOrigin(models.Model):
    origin_id = models.AutoField(primary_key=True)
    continent = models.IntegerField(choices=CONTINENT_CHOICES)
    country = models.IntegerField(choices=COUNTRY_CHOICES)
    region = models.IntegerField(choices=REGION_CHOICES)

    def get_continent_display(self):
        return dict(CONTINENT_CHOICES).get(self.continent)

    def get_country_display(self):
        return dict(COUNTRY_CHOICES).get(self.country)

    def get_region_display(self):
        return dict(REGION_CHOICES).get(self.region)

    def __str__(self):
        return (
        f"{self.get_continent_display()}, "
        f"{self.get_country_display()}, "
        f"{self.get_region_display()}"
    )


class CoffeeGrind(models.Model):
    grind_id = models.AutoField(primary_key=True)
    grind = models.IntegerField(choices=GRIND_CHOICES)

    def get_grind_display(self):
        return dict(GRIND_CHOICES).get(self.grind)

    def __str__(self):
        return self.get_grind_display()


class CoffeeSize(models.Model):
    size_id = models.AutoField(primary_key=True)
    size = models.DecimalField(null=True, max_digits=10, decimal_places=0)
    unit = models.TextField()

    def __str__(self):
        return f"{self.size} {self.unit}"


class Product(models.Model):
    product_id = models.BigAutoField(primary_key=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name="products")
    origin = models.ForeignKey(CoffeeOrigin, on_delete=models.CASCADE,
                                  null=True,
                                  related_name="products")
    grind = models.ForeignKey(CoffeeGrind, on_delete=models.CASCADE,
                                 null=True,
                                 related_name="products")
    size = models.ForeignKey(CoffeeSize, on_delete=models.CASCADE,
                                null=True,
                                related_name="products")
    manufacturer = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, blank=True)

    def get_currency_symbol(self):
        currency_dict = dict(CURRENCY_CHOICES)
        symbol = next((symbol for code, symbol in CURRENCY_SYMBOLS
                      if code == self.currency), '')
        return symbol

    def get_currency_display(self):
        return self.get_currency_symbol()

    def save(self, *args, **kwargs):
        if not self.slug or self.slug.strip() == "":
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)
    description = models.TextField()
    price = models.DecimalField(max_digits=4, decimal_places=2)
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES,
                                default='GBP')
    image = CloudinaryField('image')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.name

roastery/forms.py
import re
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'category', 'origin', 'grind', 'size', 'manufacturer',
            'name', 'description', 'price', 'currency', 'image'
            ]
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control'}),
            'origin': forms.Select(attrs={'class': 'form-control'}),
            'grind': forms.Select(attrs={'class': 'form-control'}),
            'size': forms.Select(attrs={'class': 'form-control'}),
            'manufacturer': forms.TextInput(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'currency': forms.Select(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price is not None:
            if price.as_tuple().exponent < -2:
                raise forms.ValidationError("Ensure that the price has no more"
                                            " than 2 decimal places.")

            if price <= 0:
                raise forms.ValidationError('Price must be a positive number.')

            if price > 90:
                raise forms.ValidationError('Price cannot exceed 90.')

        return price

roastery/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.urls import reverse
from .forms import ProductForm
from django.views import generic
from .models import Product, CONTINENT_CHOICES
from django.db.models import Q


def index(request):
    continents = [
        {'name': 'African', 'continent_index': 0},
        {'name': 'Asian', 'continent_index': 1},
        {'name': 'American', 'continent_index': 2},
    ]

    continent_list = []
    for continent in continents:
        image = get_continent_image(continent['continent_index'])
        continent_list.append({'name': continent['name'], 'image': image})

    return render(request, 'index.html', {'continent_list': continent_list})


def get_continent_image(continent_index):
    continent_images = {
        0: 'Relish-Coffee-Africa-Selection-300x300.webp',
        1: 'Relish-Coffee-Asian-Selection-300x300.webp',
        2: 'Relish-Coffee-American-Selection-300x300.webp'
    }

    return continent_images.get(continent_index,)


class ProductList(generic.ListView):
    queryset = Product.objects.all()
    template_name = "roastery/index.html"
    paginate_by = 6


from django.db.models import Q

def products_list(request):
    query = request.GET.get('q', '')
    continent_filter = request.GET.get('continent', '')

    products = Product.objects.all()

    if query:
        products = products.filter(Q(name__icontains=query) | Q(description__icontains=query))
    
    if continent_filter:
        products = products.filter(origin__continent=int(continent_filter))

    continent_choices = dict(CONTINENT_CHOICES)

    context = {
        'products': products,
        'query': query,
        'continent_filter': continent_filter,
        'continents': continent_choices,
    }
    return render(request, 'roastery/products_list.html', context)



def origin_products(request, continent_name=None):

    if not continent_name:
        return render(request, 'origin_products.html', {
        })

    continent_index = next((index for index, name in CONTINENT_CHOICES
                            if name == continent_name), None)
    if continent_index is None:
        products = []
    else:
        products = Product.objects.filter(origin__continent=continent_index)

    return render(request, 'origin_products.html', {
        'products': products,
        'continent_name': continent_name
    })


def product_detail(request, product_id):
    product = get_object_or_404(Product, product_id=product_id)
    currency_symbol = product.get_currency_symbol()
    success_message = request.GET.get('success_message')

    context = {
        'product': product,
        'continent_name': product.origin.get_continent_display(),
        'country_name': product.origin.get_country_display(),
        'currency_symbol': currency_symbol,
        'success_message': success_message,
    }
    return render(request, 'product_detail.html', context)


@login_required
@permission_required('roastery.add_product', raise_exception=True)
def create_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(f'{reverse("manage_products")}?'
                            f'success_message=Product created successfully!')
        else:
            return render(request, 'roastery/product_form.html',
                          {'form': form})
    else:
        form = ProductForm()

    return render(request, 'roastery/product_form.html', {'form': form})


@login_required
@permission_required('roastery.manage_products', raise_exception=True)
def manage_products(request):
    products = Product.objects.all()
    success_message = request.GET.get('success_message', None)
    return render(request, 'roastery/manage_products.html',
                  {'products': products, 'success_message': success_message})


@login_required
@permission_required('roastery.change_product', raise_exception=True)
def update_product(request, product_id):
    product = get_object_or_404(Product, product_id=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect(reverse('manage_products') +
                            '?success_message=Product updated successfully!')

    else:
        form = ProductForm(instance=product)

    success_message = request.GET.get('success_message')

    return render(request, 'roastery/product_form.html', {'form': form,
                                                          'success_message':
                                                              success_message})


@login_required
@permission_required('roastery.delete_product', raise_exception=True)
def delete_product(request, product_id):
    product = get_object_or_404(Product, product_id=product_id)
    if request.method == 'POST':
        product.delete()
        return redirect(f'{reverse("manage_products")}?'
                        f'success_message=Product deleted successfully!')
    else:
        return JsonResponse({'success': False}, status=400)


def custom_permission_denied_view(request, exception):
    return render(request, '403.html', status=403)

def custom_page_not_found(request, exception):
    return render(request, '404.html', status=404)

roastery/templates/roastery/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="hero-container">
        <img class="hero-img img-fluid w-100" src="{% static 'images/Relish-hero-image.webp' %}" alt="coffee beans, cups, and coffee making utensils around scattered around the title "The Home of Coffee"">
    </div>

    <div class="content-container mt-5 clearfix">
        <!-- About Relish Section -->
        <div class="row justify-content-center py-4 py-lg-5 bg-light rounded shadow-sm mb-5">
            <div class="col-12 col-md-8 text-center">
                <h2 class="hand--written mb-3 text-primary">About Relish</h2>
                <p class="fs-5 text-muted">
                    Relish is a coffee roastery that sources coffee beans from around the world. We are dedicated to providing the best coffee experience to our customers. Our coffee beans are sourced from the best coffee farms in the world and roasted to perfection. 
                </p>
                <p class="fs-5 text-muted">
                    We offer a wide range of coffee beans from different regions, each with its unique flavor profile. Whether you are a coffee connoisseur or just starting your coffee journey, we have something for everyone. Explore our collection of coffees from around the world and find your perfect cup of coffee.
                </p>
            </div>
        </div>
    
        <!-- Our Products Section -->
        <div class="row justify-content-center py-4 py-lg-5 bg-light rounded shadow-sm">
            <div class="col-12 col-md-8 text-center">
                <h2 class="hand--written mb-3 text-primary">Our Products</h2>
                <p class="fs-5 text-muted">
                    At Relish, we take pride in offering an exceptional selection of coffee beans from various corners of the globe. Each region brings its own distinctive flavors and aromas, allowing you to experience a rich variety of coffee profiles.
                </p>
                <p class="fs-5 text-muted">
                    From the bold and earthy notes of African beans to the smooth, delicate flavors of Asian varieties, our curated range caters to every palate. Whether you're an experienced coffee enthusiast or new to the world of specialty brews, our diverse collection guarantees you'll find a blend that suits your taste.
                </p>
            </div>
        </div>
    </div>
    

        <h2 class="col-12 mt-3 text-center">Coffees of the world</h2>
        <div class="row">
            {% for continent in continent_list %}
            <div class="col-md-4 col-sm-6 col-xs-12 mb-4">
                <div class="card">
                    <div class="card-body">
                        <a href="{% url 'origin_products' continent.name %}" class="continent-link">
                        <div class="image-container">
                            <img class="img-fluid" src="{% static 'images/coffee/' %}{{ continent.image }}" alt="{{ continent.name }}">
                        </div>
                            <h2 class="card-title text-center">{{ continent.name }} Coffee</h2>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

roastery/templates/roastery/manage_products.html
{% extends 'base.html' %}
{% load static %}

{% block breadcrumbs %}
<li><a href="{% url 'home' %}" 
class="breadcrumbs-link">Home</a>&nbsp;/&nbsp;</li>
<li><a href="{% url 'manage_products' %}"class="breadcrumbs-link">Manage Products</a>&nbsp;&nbsp;</li>
{% endblock breadcrumbs %}

{% block content %}
<div class="container">
    <!-- Success message for update -->
    {% if success_message %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Product updated successfully!</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}

    <!-- Success message for delete-->
    <div id="success-message" class="alert alert-success alert-dismissible fade" role="alert" style="display: none;">
        <strong>Product deleted successfully!</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

    <h2 class="page-title">Manage Products</h2>
    <a href="{% url 'create_product' %}" class="btn btn-create mb-3">Create Product</a>
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

    <ul class="product-list">
        {% for product in products %}
            <li id="product-{{ product.product_id }}" class="product-item d-flex justify-content-between align-items-center">
                <a href="{% url 'product_detail' product.product_id %}" class="product-link">{{ product.name }}</a>
                <div class="btn-wrapper">
                    <a href="{% url 'update_product' product.product_id %}" class="btn btn-update btn-sm">Update</a>
                    <!-- Delete form -->
                    <form method="post" action="{% url 'delete_product' product.product_id %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-delete btn-sm" onclick="return confirm('Are you sure you want to delete {{ product.name }}?');">Delete</button>
                    </form>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>
  
    <script src="{% static 'js/script.js' %}"></script>
  {% endblock content %}

roastery/templates/roastery/origin_products.html
{% extends "base.html" %}
{% load static %}

{% block breadcrumbs %}
<li><a href="{% url 'home' %}" 
class="breadcrumbs-link">Home</a>&nbsp;/&nbsp;</li>
<li><a href="{% url 'origin_products' continent_name='continent_name' %}" class="breadcrumbs-link">{{ continent_name }} Coffee</a></li>
{% endblock breadcrumbs %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12 mt-3 text-center">
            <h1>{{ continent_name }} Coffee</h1>
            <div class="row">
                {% for product in products %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <a href="{% url 'product_detail' product.product_id %}" class="country-link">
                            <div class="image-container">
                                {% if "placeholder" in product.image.url %}
                                <img src="{% static 'images/placeholder.jpg' %}" alt="{{ product.name }}" class="img-fluid">
                                {% else %}
                                <img src="{{ product.image.url }}" alt="{{ product.name }}" class="img-fluid">
                                {% endif %}
                            </div>
                                <h2 class="card-title">{{ product.name|lower|capfirst}}</h2>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

roastery/templates/roastery/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block breadcrumbs %}
<li><a href="{% url 'home' %}" class="breadcrumbs-link">Home</a>
    &nbsp;/&nbsp;</li>
<li><a href="{% url 'origin_products' continent_name=continent_name %}" class="breadcrumbs-link">{{ continent_name }} Coffee</a>&nbsp;/&nbsp;</li>
<li><a href="{% url 'product_detail' product_id=product.product_id %}" class="breadcrumbs-link">{{ product.name }}</a></li>
{% endblock breadcrumbs %}

{% block content %}
<div class="container mt-3">
    <div class="row">
        <div class="col-md-6">
            {% if success_message %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{ success_message}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
            {% if "placeholder" in product.image.url %}
            <img src="{% static product.image %}" alt="{{ product.name }}" class="img-fluid">
            {% else %}
            <img src="{{ product.image.url }}" alt="{{ product.name }}" class="img-fluid">
            {% endif %}
        </div>
        <div class="col-md-6">
            <h1>{{ product.name }} -</h1>
            <p>{{ product.size | safe }}</p>
            <p>{{ product.description | safe }}</p>
            <p>Price: {{ product.get_currency_symbol }}{{ product.price }}</p>
            <form action="{% url 'bag:add_to_bag' product.product_id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Add to Basket</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

roastery/templates/roastery/product_form.html
{% extends 'base.html' %}
{% load static%}

{% block breadcrumbs %}
  <li><a href="{% url 'home' %}" 
  class="breadcrumbs-link">Home</a>&nbsp;/&nbsp;</li>
  <li><a href="{% url 'manage_products' %}" class="breadcrumbs-link">Manage Products</a>&nbsp;/&nbsp;</li>
  {% if form.instance.pk %}
    <li><a href="{% url 'update_product' product_id=form.instance.pk %}" class="breadcrumbs-link">Update Product</a></li>
  {% else %}
    <li><a href="{% url 'create_product' %}">Create Product</a></li>
  {% endif %}
{% endblock breadcrumbs %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12 mt-3">
            <div class="product_form">
                <div class="card-header">
                    <h2>{% if form.instance.pk %}Update Product{% else %}Create Product{% endif %}</h2>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data" class="my-form">
                        {% csrf_token %}
                    
                        <!-- Error messages at the top -->
                        {% if form.non_field_errors or form.errors %}
                            <div class="alert alert-danger" role="alert">
                                <strong>Please fix the following errors:</strong>
                                <ul>
                                    {% for field, errors in form.errors.items %}
                                        {% for error in errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    {% endfor %}
                                    {% if form.non_field_errors %}
                                        {% for error in form.non_field_errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    {% endif %}
                                </ul>
                            </div>
                        {% endif %}

                        {% for field in form %}
                            <div class="mb-3">
                                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                {{ field }}
                                {% if field.errors %}
                                    <div class="invalid-feedback">
                                        {% for error in field.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}


                        <button type="submit" class="btn btn-primary">
                            {% if form.instance.pk %}Update{% else %}Create{% endif %}
                        </button>
                        <a href="{% url 'manage_products' %}" class="btn btn-secondary">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

roastery/templates/roastery/products_list.html
{% extends 'base.html' %}
{% load static %}

{% block breadcrumbs %}
<li><a href="{% url 'home' %}" class="breadcrumbs-link">Home</a>
    &nbsp;/&nbsp;</li>
<li><a href="{% url 'products' %}" class="breadcrumbs-link"> Products</a>&nbsp;/&nbsp;</li>
{% endblock breadcrumbs %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center">Our Products</h1>
    
    <!-- Search and Filter Form -->
    <form method="get" class="mb-4">
        <div class="row">
            <div class="col-md-6">
                <input type="text" name="q" value="{{ query }}" class="form-control" placeholder="Search Products...">
            </div>
            <div class="col-md-4">
                <select name="continent" class="form-control">
                    <option value="">All Continents</option>
                    {% for code, name in continents.items %}
                    <option value="{{ code }}" {% if code|stringformat:"d" == continent_filter %}selected{% endif %}>{{ name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-2">
                <button type="submit" class="btn btn-primary">Filter</button>
            </div>
        </div>
    </form>
    

    <!-- Product -->
    <div class="row">
        {% for product in products %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="text-muted">Price: {{ product.get_currency_symbol }}{{ product.price }}</p>
                    <a href="{% url 'product_detail' product_id=product.product_id %}" class="btn btn-secondary me-3">View Details</a>
                    <a href="{% url 'bag:add_to_bag' product.product_id %}" class="btn btn-primary">Add to Basket</a>
                </div>
            </div>
        </div>
        {% empty %}
        <p class="text-center">No products available.</p>
        {% endfor %}
    </div>
    
</div>
{% endblock %}

roastery/templates/roastery/purchase_form.html
{% extends "base.html" %}
{% load static %}

{% block breadcrumbs %}
<li><a href="{% url 'home' %}" 
class="breadcrumbs-link">Home</a>&nbsp;/&nbsp;</li>
<li><a href="{% url 'origin_products' continent_name=continent_name %}" class="breadcrumbs-link">{{ continent_name }} Coffee</a>&nbsp;/&nbsp;</li>
<li><a href="{% url 'product_detail' product_id=product.product_id %}" class="breadcrumbs-link">{{ product.name }}</a>&nbsp;/&nbsp;</li>
<li><a href="{% url 'purchase_form' product_id=product.product_id %}" class="breadcrumbs-link">Purchase Enquiry</a></li>
{% endblock breadcrumbs %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 col-lg-6 mx-auto mt-5">
            <div class="product_form">
                <div class="card-header">
                    <h1>Purchase a bag of {{ product.name }}</h1>
                </div>
                <div class="card-body">
                    <form method="post" class="my-form">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}