bag/urls.py
from django.urls import path
from . import views

app_name = 'bag'

urlpatterns = [
    path('', views.bag_detail, name='bag_detail'),
    path('add/<int:product_id>/', views.add_to_bag, name='add_to_bag'),
    path('update/<int:item_id>/', views.update_bag_item, name='update_bag_item'),
    path('remove/<int:item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

relish/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'roastery.views.custom_page_not_found'
handler403 = 'roastery.views.custom_permission_denied_view'


urlpatterns = [
    path("admin/", admin.site.urls),
    path("summernote/", include("django_summernote.urls")),
    path("", include("roastery.urls"), name="roastery-urls"),
    path("accounts/", include("accounts.urls")),
    path("", include("django.contrib.auth.urls")),
    path("roastery/", include("roastery.urls")),
    path("", include("roastery.urls")),
    path("bag/", include("bag.urls")),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
]

templates/base.html
{% load static %}
{% url 'home' as home_url %}

<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <title>Relish</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Relish - The home of coffee.">

    <!-- Favicon -->
    <link rel="icon" href="{% static 'images/favicon/favicon.ico' %}" type="image/x-icon">

    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'images/favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'images/favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'images/favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'images/favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'images/favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'images/favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'images/favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'images/favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">

    <!-- Google Fonts CSS -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Bootstrap Icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Mailchimp CSS -->
    <link href="//cdn-images.mailchimp.com/embedcode/classic-061523.css"
    rel="stylesheet" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Custom JavaScript -->
    <link rel="stylesheet" href="{% static 'js/script.js' %}">

    <!-- Stripe -->
    <script src="https://js.stripe.com/v3/"></script>

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <!-- Logo and Breadcrumb -->
            <div class="navbar-brand">
                <a href="{% url 'home' %}" class="d-flex align-items-center">
                    <img src="{% static 'images/Relish-Logo.webp' %}" alt="Relish" class="brand-logo">
                </a>
                <h1 class="brand-name d-md-block ms-3">Relish</h1>

                <!-- Breadcrumb navigation below the logo -->
                <nav class="woocommerce-breadcrumb mt-2" aria-label="Breadcrumb">
                    <ol class="breadcrumb bg-white mb-0">
                        {% block breadcrumbs %}
                         <!-- Content Goes here -->
                        {% endblock breadcrumbs %}
                    </ol>
                </nav>
            </div>

            <!-- Bag icon -->
            <div class="bag-container">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bag:bag_detail' %}">
                            <i class="fas fa-shopping-bag"></i>
                            <span class="badge bg-danger bag-counter">
                                {{ bag_items_count }}</span>
                        </a>
                    </li>
                </ul>
            </div>

            <!-- Products Menu -->
            <div class="collapse navbar-collapse" id="navbarContent">
                <ul class="navbar-nav ms-auto list-unstyled">
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link text-dark" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fa-solid fa-box-open"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'products' %}">Products</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            

            <!-- User Menu -->
            <div class="user-menu ms-auto">
                <ul class="navbar-nav d-flex align-items-center">
                    {% if user.is_authenticated and user.is_staff %}
                    <li class="nav-item">
                        <a href="{% url 'manage_products' %}">
                            <i class="fa-solid fa-gear"></i>
                        </a>
                    </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link text-dark" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fa fa-user"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                            <li><a class="dropdown-item" href="{% url 'profile' %}">Profile</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link text-dark" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fa fa-user"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                            <li><a class="dropdown-item" href="{% url 'register' %}">Register</a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>        

    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <div class="container text-center">
          <p class="mb-2" class="social">Follow us:</p>
          <div class="social-links">
            <a href="https://facebook.com" class="social-link" aria-label="Facebook" target="_blank">
              <i class="fab fa-facebook-square"></i>
            </a>
            <a href="https://twitter.com" class="social-link" aria-label="Twitter" target="_blank">
              <i class="fab fa-twitter-square"></i>
            </a>
            <a href="https://instagram.com" class="social-link" aria-label="Instagram" target="_blank">
              <i class="fab fa-instagram-square"></i>
            </a>
          </div>
        </div>


        <div class="container">
            <div class="row justify-content-center">
              <div class="col-12 col-sm-10 col-md-8">
                <!-- Mailchimp Signup Form -->
                <div id="mc_embed_shell">
                  <div id="mc_embed_signup" class="p-3 border rounded shadow-sm bg-light">
                    <form action="https://herokuapp.us22.list-manage.com/subscribe/post?u=5dd996439f783d550f94e0442&amp;id=adf491b02d&amp;f_id=00aed4e1f0" 
                          method="post" 
                          id="mc-embedded-subscribe-form" 
                          name="mc-embedded-subscribe-form" 
                          class="validate" 
                          target="_blank">
                      <div id="mc_embed_signup_scroll">
                        <h2 class="text-center mb-3">Subscribe to our newsletter</h2>
                        <p class="text-center">Get the latest news and offers from Relish</p>
                        <div class="indicates-required text-center">
                          <span class="asterisk">*</span> indicates required
                        </div>
                        <div class="mc-field-group my-3">
                          <label for="mce-EMAIL" class="form-label">Email Address <span class="asterisk">*</span></label>
                          <input type="email" name="EMAIL" class="form-control required email" id="mce-EMAIL" required>
                        </div>
                        <div id="mce-responses" class="clear">
                          <div class="response" id="mce-error-response" style="display: none;"></div>
                          <div class="response text-success" id="mce-success-response" style="display: none;"></div>
                        </div>
                        <div aria-hidden="true" style="position: absolute; left: -5000px;">
                          <input type="text" name="b_5dd996439f783d550f94e0442_adf491b02d" tabindex="-1">
                        </div>
                        <div class="text-center mt-4">
                          <button type="submit" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary">
                            Subscribe
                          </button>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
        </div>
              
    </footer>

    {% block postloadjs %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static '/js/script.js' %}"></script>

    <!-- Mail Chimp -->
    <script type="text/javascript"
    src="//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js">
    </script>
    <script type="text/javascript">
        (function($) {
            window.fnames = new Array();
            window.ftypes = new Array();
            fnames[0]='EMAIL';
            ftypes[0]='email';
            fnames[1]='FNAME';
            ftypes[1]='text';
            fnames[2]='LNAME';
            ftypes[2]='text';
            fnames[3]='ADDRESS';
            ftypes[3]='address';
            fnames[4]='PHONE';
            ftypes[4]='phone';
            fnames[5]='BIRTHDAY';
            ftypes[5]='birthday';
            fnames[6]='COMPANY';
            ftypes[6]='text';
        }(jQuery));
        var $mcj = jQuery.noConflict(true);
    </script>
    {% endblock postloadjs %}
          
</body>

</html>